### PR TITLE
Create reactive-composite-collections

### PR DESCRIPTION
**Pull request by bradphelan**

### CODE REVIEW

**Comment by ghuntley** [comment]
Thanks @bradphelan 👍

**Comment by bradphelan** [comment]
If you care to give the library a spin I would appreciate it. The cleverness probably has some downsides as well. Under the hood it's all ImmutableCollections and then to convert it to IObservableCollection I have to do diffs against pairs of ImmutableLists. Not sure how it scales to millions of rows but that is not currently my use case :)

**Comment by ghuntley** [comment]
Won't be in a position for a while @bradphelan. Doing more community mgmt, fixing new developer experience (docs/samples) but will forward any and all feedback from users to you (via DM).

**Comment by bradphelan** [comment]
OK :)

**Pull request merged**
