### PR TITLE
remove link (aspnet-logger.md)

### PR DESCRIPTION
**Pull request by Arhell**
upda issue https://github.com/reactiveui/website/issues/594

### CODE REVIEW

**Comment by dpvreony** [comment]
this is out of date due to https://github.com/reactiveui/splat#microsoftextensionslogging ?

**Comment by Arhell** [comment]
What suggestions? Delete this file?

**Comment by dpvreony** [comment]
it might be worth merging this page and https://www.reactiveui.net/docs/handbook/logging/observable-logger under a page of something like "Choosing your logging output"

I would reference the new Splat packages but the post and observable logger project are still good sources of understanding on how you can do custom logging if still required, so keep it as something worth reading for those who want some insight and learning.

some of these bits came from splat was going through a lean spell of maintenance.

https://www.reactiveui.net/docs/handbook/logging/observable-logger needs looking at because it targets ReactiveUI 7 so raised https://github.com/reactiveui/splat/issues/724

**Comment by glennawatson** [comment]
@dpvreony If the content needs rewriting might be best if one of us do it. @Arhell sort of specialises in minor changes and does a lot of CSS changes.

**Comment by dpvreony** [comment]
i will sort, i did actually mean to put that and tag you to ensure it made sense.

**Comment by glennawatson** [comment]
Yeah we've taken over stuff from @jcmm33 before, he is available on the slack channel to DM.

**Comment by glennawatson** [comment]
Just recommend deleting the link for now. We'll chase up with @jcmm33 offline.

**Comment by Arhell** [comment]
@glennawatson  done

**Review by glennawatson — APPROVED** [review]

**Comment by glennawatson** [comment]
Thanks :)

**Pull request merged**
