### PR TITLE
docs: added uno platform guidance

### PR DESCRIPTION
**Pull request by ghuntley**
**What kind of change does this PR introduce?**

docs: adds guidance for the uno platform

### CODE REVIEW

**Comment by glennawatson** [comment]
Let's not merge this one in until there are Uno events and someone is able to go in and tidy it up a bit on the branch.

**Comment by glennawatson** [comment]
Event packages are becoming deprecated soon. So this has some outdated advice also

**Comment by ghuntley** [comment]
Let's get this in and take a TODO to clean up `input/docs/guidelines/platform/*.md` in the future.

**Comment by glennawatson** [comment]
We have strict quality on these items now since it just we have to many support requests if there is issues. Also the fact it mentions events packages is likely to cause the user confusion since there won't be one for Uno

**Comment by glennawatson** [comment]
I'm going to revert this pr

**Pull request merged**
