### PR TITLE
More home page improvements

### PR DESCRIPTION
**Pull request by worldbeater**
image

### CODE REVIEW

**Comment by glennawatson** [comment]
How's it look with the backers on the bottom? Just looks a little odd in the middle.

**Comment by worldbeater** [comment]
image

**Comment by cabauman** [comment]
I think I like the 2nd one better (at the bottom).

**Comment by glennawatson** [comment]
Agree with the second looking better.

**Comment by RLittlesII** [comment]
I like backers at the bottom.  As a user I come to the site for information about ReactiveUI.  Not to see who gives money.

**Pull request merged**
