### PR TITLE
Accessibility add lang tag to html

### PR DESCRIPTION
**Pull request by Arhell**
**What are the main goals of this change?**
- [ ] Better readability (style, grammar, spelling...)
- [ ] Content correction (accuracy, wrong information...)
- [ ] New content

**Is this change related to any reported issue? (Optional)**
resolve https://github.com/reactiveui/website/issues/804

**Notes (Optional)**

### CODE REVIEW

**Review by ChrisPulman — CHANGES_REQUESTED** [review]
Please could we move the `partials` folder and contents into the existing `template` folder so that we only have one additional theme template extension, thank you.

Could you also confirm that the output is achieving the desired result, as far as I see there is no change between original and new.
Perhaps a screenshot showing the desired change is active...
run `docfx reactiveui/docfx.json --serve` to see the output from a CLI

**Comment by ChrisPulman** [comment]
https://dotnet.github.io/docfx/tutorial/intro_template.html
@Arhell Hopefully this will help you to achieve what you wanted.

**Review by Arhell — COMMENTED** [review]
@ChrisPulman thanks, did everything in the best possible way.

I saw how you updated the site, thank you, a lot of work has been done.

I am also currently updating sites on docusaurus to version 3. There are also some nuances.

**Review by glennawatson — APPROVED** [review]

**Comment by glennawatson** [comment]
We are also doing a lot of content work at the moment. Lots of old content that doesn't make sense anymore, especially in the contributor area. We tried statiq which was produced by the same person who made our last document engine but we never got stable results.

**Comment by Arhell** [comment]
> We are also doing a lot of content work at the moment. Lots of old content that doesn't make sense anymore, especially in the contributor area. We tried statiq which was produced by the same person who made our last document engine but we never got stable results.

Yes, I saw it, it was not easy.
In any case, updating is not an easy thing, but in my opinion it is necessary, new technologies, convenience and much more.

**Review by ChrisPulman — APPROVED** [review]
This is a lot simpler 😁, thank you for finding this, it's much better than adjusting the template.

**Comment by Arhell** [comment]
> This is a lot simpler 😁, thank you for finding this, it's much better than adjusting the template.

Agree

**Pull request merged**
