### PR TITLE
Document ReactiveUI.Fody OAPH getters

### PR DESCRIPTION
**Pull request by worldbeater**
**What are the main goals of this change?**
- [x] Content correction (accuracy, wrong information...)

**Notes (Optional)**

Recently discovered, that the code generated by `ReactiveUI.Fody` never throws `NullReferenceException`s (and that's good!), because it contains a null check and returns `default(T)` if `ObservableAsPropertyHelper<T>` isn't yet initialized:

```cs
// Decompiled with https://github.com/icsharpcode/AvaloniaILSpy
[ObservableAsProperty]
public bool HasErrorMessage
{
	[CompilerGenerated]
	get
	{
		ObservableAsPropertyHelper<bool> observableAsPropertyHelper = $HasErrorMessage;
		if (observableAsPropertyHelper == null)
		{
			return false;
		}
		return observableAsPropertyHelper.Value;
	}
}
```

Keeping this in mind is useful when there are properties that depend on each other, and hence, one of the properties has to be initialized later than the other may need its value. Let's make the documentation more accurate regarding this point!

### CODE REVIEW

**Comment by glennawatson** [comment]
Hmmmm that default functionality sounds wrong

**Comment by worldbeater** [comment]
Decompiled [this class](https://github.com/worldbeater/Camelotia/blob/main/src/Camelotia.Presentation/ViewModels/DirectAuthViewModel.cs) with [ILSpy](https://github.com/icsharpcode/AvaloniaILSpy), and got [the following code](https://gist.github.com/worldbeater/d93c5edcaa4ec28b1fc0b37505b750b3)! Probably that's due to [`EmitDefaultValue`](https://github.com/reactiveui/ReactiveUI/blob/main/src/ReactiveUI.Fody/ObservableAsPropertyWeaver.cs#L116) or something

**Comment by glennawatson** [comment]
Yeah not saying it doesn't do it just that null reference is likely better in some ways since this functionality could lead to subtle bugs

**Comment by worldbeater** [comment]
Avoiding `NRE`s can be useful in situations like in this [code snippet](https://github.com/worldbeater/Camelotia/blob/main/src/Camelotia.Presentation/ViewModels/ProviderViewModel.cs#L57):
```cs
_refresh.Select(files => files.OrderByDescending(file => file.Name))
    .Where(files => Files == null || !files.SequenceEqual(Files))
    .ToPropertyEx(this, x => x.Files);
```
Here, I need to check if the `Files` oaph is null before assigning a value to it. With `NRE`s enabled, this won't be possible — the `ObservableAsPropertyHelper<T>` is generated by the compiler and is hidden, and accessing a property directly throws an exception. 

Another example. This [`canInteract`](https://github.com/worldbeater/Camelotia/blob/main/src/Camelotia.Presentation/ViewModels/ProviderViewModel.cs#L51) property depends on [`IsVisible`](https://github.com/worldbeater/Camelotia/blob/main/src/Camelotia.Presentation/ViewModels/ProviderViewModel.cs#L45) properties of the two nested view models, and that view models depend on the [`canInteract`](https://github.com/worldbeater/Camelotia/blob/main/src/Camelotia.Presentation/ViewModels/RenameFileViewModel.cs#L42) property of the root view model. So one of the oaph properties has to be initialized earlier. Probably worth declaring an oaph with a null coalescing operator explicitly in such cases, for sure. Or changing the way how these properties relate to each other by introducing a mediator `Subject<T>` etc. However I liked how it worked without additional efforts yesterday :smiley:

**Pull request merged**
