### PR TITLE
adds /docs/thanks page (fixes #41)

### LINKED ISSUE #41: add /docs/thanks page
See https://curl.haxx.se/docs/thanks.html - generate it from
- reactiveui/reactiveui commits
- reactiveui/website commits

### PR DESCRIPTION
**Pull request by dabutvin**
image

### CODE REVIEW

**Comment by ghuntley** [comment]
@dabutvin this is a _really_ interesting idea. I dig this a-lot. I think it would be better if the grouping via repo was removed/merge everyone (website + project source code) into a single listing of avatars w/links to their GitHub account.

Anyway contributors to the project are listed over at https://reactiveui.net/contribute/#contributors but it's a single image insert. Your implementation is much better. How about we replace that implementation with your implementation?

**Comment by ghuntley** [comment]
Hmm I forgot about #41. I suppose we could burn /contribute/#contributors and instead have it as `/docs/thanks`? What do you think.

**Comment by dabutvin** [comment]
I think it would be good to dynamically bring in all contributors on their own thank you page.
Making it one big group makes sense probably.

I didn't realize there already was a contributors section, I can tear that down if you want and update to a single section and order alphabetically instead of by contribution count. 

Sounds good?

**Comment by ghuntley** [comment]
👍 let's make it a seperate page as you have done
👍 order alphabetically and as single section
🔥 delete the `/contribute/#contributors` section and hints on that page that <3 people who contribute and they can be found on the credits/thank-you page.

**Comment by dabutvin** [comment]
I've updated to be a single sorted list of contributors ;)

image

**Comment by ghuntley** [comment]
🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 

Awesome - thank-you @dabutvin.

**Pull request merged**
