### PR TITLE
make social metadata less annoying

### PR DESCRIPTION
**Pull request by ghuntley**
image

Took a quick stab at this, if someone wants to help finish it off that would be A+.  What I'm after is the ability to define additional Wyam metadata on a per-page basis that when defined overrides/displays the value instead of the defaults.

### CODE REVIEW

**Comment by rvlieshout** [comment]
Perhaps the long summary could be shortened. The 'inspired by' part could be a section on the about page.

**Comment by ghuntley** [comment]
I think you're right - that entire verbiage could be much much better. Consider the metadata w/React - it's very succinct.

image

Any suggestions on how to improve the messaging?

**Comment by olevett** [comment]
Have made a pass at the description bit, which should now work as expected (I also added the meta description tag into this block). Haven't done any refactoring of the wording though.

@ghuntley is this the sort of thing you're after?

**Comment by ghuntley** [comment]
@olevett yup. It didn't occur to me at the time that we could repurpose `DocKeys.Description` for this. Thank-you. Let's 🚢

**Pull request merged**
