### PR TITLE
Feature: Convert Wyam to DocFx

### PR DESCRIPTION
**Pull request by ChrisPulman**
**What are the main goals of this change?**
- [x] Better readability (style, grammar, spelling...)
- [x] Content correction (accuracy, wrong information...)
- [x] New content

**Is this change related to any reported issue? (Optional)**

#789
#776
#770
#441
#682 - Remove link
#744 - Update links
#758
#349 - Use [ReactiveMarbles.ObservableEvents.SourceGenerator](https://www.nuget.org/packages/ReactiveMarbles.ObservableEvents.SourceGenerator/)

**Notes (Optional)**

### CODE REVIEW

**Comment by glennawatson** [comment]
Be worth adding a .gitignore entry for the `.vs` folder, maybe use a copy paste of the standard visualstudio one ontop of whatever our engine we are using to generate the code is now.

**Comment by dpvreony** [comment]
you can avoid compiling all of the src projects and use the nuget packages. should drastically reduce your build time.

see https://github.com/dpvreony/documentation/blob/main/src/upstream/upstream.csproj for an example.
also note the docfx project does not have a project dependency on upstream to avoid framework issues. it instead uses a postbuild dependency in the solution https://github.com/dpvreony/documentation/blob/4ac1ce53705f6a263a3d6f2a17783a9f55b76278/src/DPVreony.Documentation.sln#L7

**Comment by ChrisPulman** [comment]
> you can avoid compiling all of the src projects and use the nuget packages. should drastically reduce your build time.
> 
> see https://github.com/dpvreony/documentation/blob/main/src/upstream/upstream.csproj for an example. also note the docfx project does not have a project dependency on upstream to avoid framework issues. it instead uses a postbuild dependency in the solution https://github.com/dpvreony/documentation/blob/4ac1ce53705f6a263a3d6f2a17783a9f55b76278/src/DPVreony.Documentation.sln#L7

Thank you David It's taking a long time for some reason, it only takes 10 minutes at the most too build and create the whole thing on my laptop. I will definitely consider the nuget option It's probably best if it's based on the last release anyway rather than what could be an updated in-between version.
Thank you for the pointers the lib project based version looks like a better option. I will fix up the code that's been flagged as an issue before switching to nuget packages as I may not get the same pointers using nuget.

**Comment by ChrisPulman** [comment]
> you can avoid compiling all of the src projects and use the nuget packages. should drastically reduce your build time.
> 
> see [dpvreony/documentation@`main`/src/upstream/upstream.csproj](https://github.com/dpvreony/documentation/blob/main/src/upstream/upstream.csproj?rgh-link-date=2023-10-30T20%3A49%3A00Z) for an example. also note the docfx project does not have a project dependency on upstream to avoid framework issues. it instead uses a postbuild dependency in the solution [dpvreony/documentation@`4ac1ce5`/src/DPVreony.Documentation.sln#L7](https://github.com/dpvreony/documentation/blob/4ac1ce53705f6a263a3d6f2a17783a9f55b76278/src/DPVreony.Documentation.sln#L7)

It looks like the build is not an issue it takes 16 minutes in the cloud compared to 4 minutes on my laptop, but the overall build only takes 10 minutes from start to finish having a running website on my laptop, the issue seems to be that it's taking a long time to build the website API docs in the cloud. So far, I haven't seen it complete in less than 5 hours at which point I cancelled it. I separated the website build from the API build to see the difference and where it's getting stuck.

**Review by glennawatson — APPROVED** [review]

**Pull request merged**
