### PR TITLE
[WIP] Changed spelling on cancel (#90)

### LINKED ISSUE #90: Issue with docs/handbook/commands/canceling.md
In the last part, where does the CancellationToken come from? where is it created?

**EDIT:** I successfully created a Cancel command with the docs :) Sorry, I didn't see that the CancellationToken was implicit in the StartAsync call.

BTW, there's a typo: sometimes the code says "cancelable" and sometimes it is "cancellable". Please, fix it.

### PR DESCRIPTION
**Pull request by RLittlesII**
Resolves #90

### CODE REVIEW

**Comment by glennawatson** [comment]
Are we doing  American english or British english? Seems single L is American english.

**Comment by glennawatson** [comment]
This is something that came up before when I was editing one of Geoff media announcements, eg which form of English we should use since he was using Australian english. We should probably document a standard in that regards.

**Comment by RLittlesII** [comment]
I am not sure which version of English we should go with.  In this specific instance, it is odd (and I've had this conversation with other devs) that the .NET Framework delivered `CancellationToken` is spell with two l's, but everything in the file that references cancelation is spelled with one.


That said, I'll defer this until we verify what our standard English will be, but I that is a horse of a different colour. 😉

**Comment by glennawatson** [comment]
This is waiting on https://github.com/reactiveui/rfcs/issues/11 to resolve.

**Comment by RLittlesII** [comment]
@glennawatson I am going to close this, as the RFC is leaning towards leaving the spellings the way they are anyway.

**Pull request closed without merging**
