### PR TITLE
adds 'Create Issue' link to Infobar (fixes #61)

### LINKED ISSUE #61: Add link that when user clicks on creates GitHub issue for the page
This creates a product feedback loop and signifies that we want this sort of feedback.

image

See https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/

https://github.com/kubernetes/website/issues/new?title=Issue%20with%20k8s.io/docs/concepts/overview/what-is-kubernetes/

ps; appears it possible to add `&body=blah` to the url to pre-fill the message template.

### PR DESCRIPTION
**Pull request by dabutvin**
- overrides the infobar from https://github.com/Wyamio/Wyam/blob/master/themes/Docs/Samson/Shared/_Infobar.cshtml

### CODE REVIEW

**Comment by dabutvin** [comment]
I don't think it would be a DocKey given the list of choices
https://wyam.io/api/wyam.docs/docskeys/

We could probably make our own constant just to get the strings in one place

**Comment by olevett** [comment]
I think making our own constant (or at least, a string in there, I think the Settings dictionary should take that) sounds good.

I think it'd be nicer to have all the config in one place.

**Comment by dabutvin** [comment]
@olevett  I updated to move the Create Issue setting into `config.wyam`

**Comment by dabutvin** [comment]
image

image

**Comment by olevett** [comment]
That looks great to me, thanks :)

**Pull request merged**
