### PR TITLE
Bring DynamicData docs

### PR DESCRIPTION
**Pull request by worldbeater**
https://github.com/reactiveui/website/issues/156

### CODE REVIEW

**Comment by glennawatson** [comment]
I don't really want a copy of the documentation for DD over here. Just direct the user over there with a overall statement what it does (eg a paragraph or two)

**Comment by glennawatson** [comment]
https://github.com/RolandPheasant/DynamicData/wiki/Introduction-for-ReactiveUI-users

That was the document Rodney meant to be brought across btw but as I mentioned would require changes to remove the discussion about how to use DynamicData with the ReativeList.

**Comment by worldbeater** [comment]
@glennawatson so should we copy-paste the content from the "Introduction for ReactiveUI users" page (removing all references to ReactiveList) or should we edit it right in DynamicData repo? 🤔

**Comment by glennawatson** [comment]
If I was doing this myself I would bring that document from the Wiki in as a base. 

I would talk about how in DD everything works around a IObservable<IChangeSet<T>> and how there are a number of internal observable aware collections, but how most of the time DD will output to a ReadonlyObservableCollection.

I would then talk about some common scenarios how RxList did stuff, eg, changes, count changes and stuff, and how to achieve the same in DD.

Then I would also talk about alternatives to the IReactiveDerivedList and the different operations.

So I potentially would making it more like a "porting" guide to the user how it works.

**Comment by glennawatson** [comment]
But I would start as the guide to that RxUI wiki page, and put it locally here, then get Roland to redirect it to our website.

**Comment by RLittlesII** [comment]
Might be worth putting an issue on DD to setup the redirect and reference this issue.

**Comment by glennawatson** [comment]
Will do that after we got some content for them to redirect to :)

**Pull request closed without merging**
