### PR TITLE
Added shadow to differentiate navigation menu from page in mobile view

### PR DESCRIPTION
**Pull request by AkashGutha**
Related to #22

### CODE REVIEW

**Comment by ghuntley** [comment]
Howdy @AkashGutha thanks for taking a stab at this. The drop-down when using mobile view is 👍 not too sure about iPad and desktop breakpoints though. 

image

image

image

**Comment by AkashGutha** [comment]
@ghuntley wasn't able to test this locally. Running a Macbook.
is there a way I can test this branch online?

**Comment by AkashGutha** [comment]
This should have fixed the issue we were facing.

**Comment by olevett** [comment]
Looks pretty good to me :)

I think as part of the bootstrap includes, we've got some media breakpoints that should be consistent with where the menu breakpoints, so it might be a little neater to do something like

```
@media(max-width: @screen-xs-max) {
  .main-header .navbar .navbar-collapse{
    box-shadow: 0 5px 10px lightgray;
  }
}
```

**Comment by AkashGutha** [comment]
I went the other way around @screen-md-min. the style sheet was already following mobile first approach.

**Comment by olevett** [comment]
Cool, thanks for this :)

**Pull request merged**
