### PR TITLE
adds GitHub link to main nav (fixes #58)

### LINKED ISSUE #58: Link to Github should be front and foremost.
Currently the link to the github repo is buried two pages deep at the bottom of a list. Given that http:\\reactiveui.net is the top google hit for ``reactiveui``

image

then clicking through that to find the repository is non obvious

image

I would suggest using one of these icons top right or at the top level menu if possible to link directly to the github page.

https://github.com/logos

### PR DESCRIPTION
**Pull request by dabutvin**

### CODE REVIEW

**Comment by dabutvin** [comment]
screenshots for design review:

image

image

image
image

**Comment by olevett** [comment]
Thanks for this @dabutvin, looks good to me, after someone more design-y to double check though

**Comment by dabutvin** [comment]
resolved conflicts and removed underline from hover on GitHub icon

**Comment by olevett** [comment]
Thanks for this (and sorry for making your merge a little more complicated!)

Looks good :)

**Pull request merged**
